Repository egc-decide-trebujena/decide, pull requests merged in 2022-11, with the labels that each got.

#8 Feature/005
  decide/authentication/form.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/visualizer/templates/signup.html
Labels: enhancement

#99 FIX: FIxed HTML
  decide/booth/templates/booth/booth.html
Labels: bug

#100 FEAT: Adapted the HTML
  decide/booth/templates/booth/booth.html
  decide/visualizer/templates/visualizer/visualizer.html
Labels: enhancement

#119 FEAT: Removed wrong PR from postproc
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/dashboard/__init__.py
  decide/dashboard/admin.py
  decide/dashboard/apps.py
  decide/dashboard/migrations/0001_initial.py
  decide/dashboard/migrations/0002_auto_20221113_0925.py
  decide/dashboard/migrations/__init__.py
  decide/dashboard/models.py
  decide/dashboard/templates/dashboard/dashboard.html
  decide/dashboard/templates/dashboard_with_pv.html
  decide/dashboard/tests.py
  decide/dashboard/urls.py
  decide/dashboard/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/store/views.py
  decide/visualizer/views.py
Labels: bug, enhancement

#135 TEST: Test order votation
  decide/postproc/tests.py
  decide/voting/tests.py
Labels: test
